export const models = [
  {
    name: 'o1-preview',
    label: 'o1-preview',
    provider: 'BothubRu',
    maxTokenAllowed: 32768,
  },
  {
    name: 'o1-mini',
    label: 'o1-mini',
    provider: 'BothubRu',
    maxTokenAllowed: 65536,
  },
  {
    name: 'gpt-4o',
    label: 'gpt-4o',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4o-mini',
    label: 'gpt-4o-mini',
    provider: 'BothubRu',
    maxTokenAllowed: 16384,
  },
  {
    name: 'gpt-4-turbo',
    label: 'gpt-4-turbo',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4',
    label: 'gpt-4',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'o1-preview-2024-09-12',
    label: 'o1-preview-2024-09-12',
    provider: 'BothubRu',
    maxTokenAllowed: 32768,
  },
  {
    name: 'o1-mini-2024-09-12',
    label: 'o1-mini-2024-09-12',
    provider: 'BothubRu',
    maxTokenAllowed: 65536,
  },
  {
    name: 'gpt-4o-2024-11-20',
    label: 'gpt-4o-2024-11-20',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4o-2024-08-06',
    label: 'gpt-4o-2024-08-06',
    provider: 'BothubRu',
    maxTokenAllowed: 16384,
  },
  {
    name: 'gpt-4o-2024-05-13',
    label: 'gpt-4o-2024-05-13',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4o:extended',
    label: 'gpt-4o:extended',
    provider: 'BothubRu',
    maxTokenAllowed: 64000,
  },
  {
    name: 'gpt-4o-mini-2024-07-18',
    label: 'gpt-4o-mini-2024-07-18',
    provider: 'BothubRu',
    maxTokenAllowed: 16384,
  },
  {
    name: 'gpt-4-32k',
    label: 'gpt-4-32k',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4-turbo-preview',
    label: 'gpt-4-turbo-preview',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4-turbo-2024-04-09',
    label: 'gpt-4-turbo-2024-04-09',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4-1106-preview',
    label: 'gpt-4-1106-preview',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4-0125-preview',
    label: 'gpt-4-0125-preview',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4-0613',
    label: 'gpt-4-0613',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'gpt-4-32k-0314',
    label: 'gpt-4-32k-0314',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-4-0314',
    label: 'gpt-4-0314',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gpt-3.5-turbo',
    label: 'gpt-3.5-turbo',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'claude-3.5-sonnet',
    label: 'claude-3.5-sonnet',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'claude-3.5-haiku',
    label: 'claude-3.5-haiku',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'claude-3-opus',
    label: 'claude-3-opus',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'claude-3.5-sonnet-20240620',
    label: 'claude-3.5-sonnet-20240620',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'claude-3.5-haiku-20241022',
    label: 'claude-3.5-haiku-20241022',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'lfm-7b',
    label: 'lfm-7b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'lfm-40b',
    label: 'lfm-40b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'lfm-3b',
    label: 'lfm-3b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-1.1-pro-ultra',
    label: 'flux-1.1-pro-ultra',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-1.1-pro',
    label: 'flux-1.1-pro',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-pro',
    label: 'flux-pro',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-dev',
    label: 'flux-dev',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-schnell',
    label: 'flux-schnell',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-dev-lora',
    label: 'flux-dev-lora',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-dev-multi-lora',
    label: 'flux-dev-multi-lora',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-schnell-lora',
    label: 'flux-schnell-lora',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-pulid',
    label: 'flux-pulid',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-dev-realism',
    label: 'flux-dev-realism',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-dev-controlnet',
    label: 'flux-dev-controlnet',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'grok-beta',
    label: 'grok-beta',
    provider: 'BothubRu',
    maxTokenAllowed: 131072,
  },
  {
    name: 'deepseek-r1-distill-llama-70b',
    label: 'deepseek-r1-distill-llama-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'deepseek-r1',
    label: 'deepseek-r1',
    provider: 'BothubRu',
    maxTokenAllowed: 8000,
  },
  {
    name: 'deepseek-chat-v2.5',
    label: 'deepseek-chat-v2.5',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'deepseek-chat',
    label: 'deepseek-chat',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'dall-e-3',
    label: 'dall-e-3',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gemini-pro-1.5',
    label: 'gemini-pro-1.5',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'gemini-flash-1.5-8b',
    label: 'gemini-flash-1.5-8b',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'gemini-flash-1.5',
    label: 'gemini-flash-1.5',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'gemini-2.0-flash-thinking-exp:free',
    label: 'gemini-2.0-flash-thinking-exp:free',
    provider: 'BothubRu',
    maxTokenAllowed: 8000,
  },
  {
    name: 'learnlm-1.5-pro-experimental:free',
    label: 'learnlm-1.5-pro-experimental:free',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'gemini-flash-1.5-8b-exp',
    label: 'gemini-flash-1.5-8b-exp',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'gemma-2-27b-it',
    label: 'gemma-2-27b-it',
    provider: 'BothubRu',
    maxTokenAllowed: 8192,
  },
  {
    name: 'gemma-2-9b-it',
    label: 'gemma-2-9b-it',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'gemma-2-9b-it:free',
    label: 'gemma-2-9b-it:free',
    provider: 'BothubRu',
    maxTokenAllowed: 2048,
  },
  {
    name: 'qwq-32b-preview',
    label: 'qwq-32b-preview',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'eva-qwen-2.5-72b',
    label: 'eva-qwen-2.5-72b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'eva-qwen-2.5-32b',
    label: 'eva-qwen-2.5-32b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'qwen-2.5-72b-instruct',
    label: 'qwen-2.5-72b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'qwen-2.5-coder-32b-instruct',
    label: 'qwen-2.5-coder-32b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'qwen-2.5-7b-instruct',
    label: 'qwen-2.5-7b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'qwen-2-vl-72b-instruct',
    label: 'qwen-2-vl-72b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'qwen-2-7b-instruct',
    label: 'qwen-2-7b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'qwen-2-vl-7b-instruct',
    label: 'qwen-2-vl-7b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'qwen-2-72b-instruct',
    label: 'qwen-2-72b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'eva-llama-3.33-70b',
    label: 'eva-llama-3.33-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'llama-3.3-70b-instruct',
    label: 'llama-3.3-70b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'llama-3.2-11b-vision-instruct',
    label: 'llama-3.2-11b-vision-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 131072,
  },
  {
    name: 'llama-3.2-3b-instruct:free',
    label: 'llama-3.2-3b-instruct:free',
    provider: 'BothubRu',
    maxTokenAllowed: 2048,
  },
  {
    name: 'llama-3.2-1b-instruct:free',
    label: 'llama-3.2-1b-instruct:free',
    provider: 'BothubRu',
    maxTokenAllowed: 2048,
  },
  {
    name: 'llama-3.2-90b-vision-instruct',
    label: 'llama-3.2-90b-vision-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'llama-3.2-3b-instruct',
    label: 'llama-3.2-3b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 131072,
  },
  {
    name: 'llama-3.2-1b-instruct',
    label: 'llama-3.2-1b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 131072,
  },
  {
    name: 'llama-3.2-90b-vision-instruct:free',
    label: 'llama-3.2-90b-vision-instruct:free',
    provider: 'BothubRu',
    maxTokenAllowed: 2048,
  },
  {
    name: 'llama-3.1-lumimaid-8b',
    label: 'llama-3.1-lumimaid-8b',
    provider: 'BothubRu',
    maxTokenAllowed: 2048,
  },
  {
    name: 'llama-3.2-11b-vision-instruct:free',
    label: 'llama-3.2-11b-vision-instruct:free',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'llama-3.1-lumimaid-70b',
    label: 'llama-3.1-lumimaid-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 2048,
  },
  {
    name: 'llama-3.1-sonar-huge-128k-online',
    label: 'llama-3.1-sonar-huge-128k-online',
    provider: 'BothubRu',
    maxTokenAllowed: 127072,
  },
  {
    name: 'llama-3.1-405b',
    label: 'llama-3.1-405b',
    provider: 'BothubRu',
    maxTokenAllowed: 32768,
  },
  {
    name: 'llama-3.1-sonar-large-128k-chat',
    label: 'llama-3.1-sonar-large-128k-chat',
    provider: 'BothubRu',
    maxTokenAllowed: 131072,
  },
  {
    name: 'llama-3.1-405b-instruct:free',
    label: 'llama-3.1-405b-instruct:free',
    provider: 'BothubRu',
    maxTokenAllowed: 4000,
  },
  {
    name: 'llama-3.1-70b-instruct',
    label: 'llama-3.1-70b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 131072,
  },
  {
    name: 'llama-3.1-sonar-small-128k-chat',
    label: 'llama-3.1-sonar-small-128k-chat',
    provider: 'BothubRu',
    maxTokenAllowed: 131072,
  },
  {
    name: 'llama-3.1-405b-instruct',
    label: 'llama-3.1-405b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 32000,
  },
  {
    name: 'llama-3.1-8b-instruct:free',
    label: 'llama-3.1-8b-instruct:free',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'llama-3.1-sonar-large-128k-online',
    label: 'llama-3.1-sonar-large-128k-online',
    provider: 'BothubRu',
    maxTokenAllowed: 127072,
  },
  {
    name: 'llama-3.1-sonar-small-128k-online',
    label: 'llama-3.1-sonar-small-128k-online',
    provider: 'BothubRu',
    maxTokenAllowed: 127072,
  },
  {
    name: 'llama-3.1-70b-instruct:free',
    label: 'llama-3.1-70b-instruct:free',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'llama-3.1-8b-instruct',
    label: 'llama-3.1-8b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 100000,
  },
  {
    name: 'llama-3.1-70b-instruct:nitro',
    label: 'llama-3.1-70b-instruct:nitro',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'llama-3.1-405b-instruct:nitro',
    label: 'llama-3.1-405b-instruct:nitro',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'llama-3.1-nemotron-70b-instruct',
    label: 'llama-3.1-nemotron-70b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'stable-diffusion-3',
    label: 'stable-diffusion-3',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mn-inferor-12b',
    label: 'mn-inferor-12b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mistral-large-2411',
    label: 'mistral-large-2411',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mistral-large-2407',
    label: 'mistral-large-2407',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'pixtral-large-2411',
    label: 'pixtral-large-2411',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mixtral-8x22b-instruct',
    label: 'mixtral-8x22b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 65536,
  },
  {
    name: 'ministral-8b',
    label: 'ministral-8b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mistral-nemo',
    label: 'mistral-nemo',
    provider: 'BothubRu',
    maxTokenAllowed: 128000,
  },
  {
    name: 'pixtral-12b',
    label: 'pixtral-12b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'ministral-3b',
    label: 'ministral-3b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mixtral-8x7b-instruct',
    label: 'mixtral-8x7b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 32768,
  },
  {
    name: 'mixtral-8x7b-instruct:nitro',
    label: 'mixtral-8x7b-instruct:nitro',
    provider: 'BothubRu',
    maxTokenAllowed: 32768,
  },
  {
    name: 'mixtral-8x7b',
    label: 'mixtral-8x7b',
    provider: 'BothubRu',
    maxTokenAllowed: 32768,
  },
  {
    name: 'codestral-mamba',
    label: 'codestral-mamba',
    provider: 'BothubRu',
    maxTokenAllowed: 256000,
  },
  {
    name: 'mistral-7b-instruct-v0.3',
    label: 'mistral-7b-instruct-v0.3',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mistral-large',
    label: 'mistral-large',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mistral-7b-instruct',
    label: 'mistral-7b-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mistral-7b-instruct:nitro',
    label: 'mistral-7b-instruct:nitro',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'codestral-2501',
    label: 'codestral-2501',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'tts-1-hd-1106',
    label: 'tts-1-hd-1106',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'tts-1-1106',
    label: 'tts-1-1106',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'tts-1-hd',
    label: 'tts-1-hd',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'tts-1',
    label: 'tts-1',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'whisper-1',
    label: 'whisper-1',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'rogue-rose-103b-v0.2:free',
    label: 'rogue-rose-103b-v0.2:free',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'midnight-rose-70b',
    label: 'midnight-rose-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'magnum-v4-72b',
    label: 'magnum-v4-72b',
    provider: 'BothubRu',
    maxTokenAllowed: 1024,
  },
  {
    name: 'magnum-v2-72b',
    label: 'magnum-v2-72b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'rocinante-12b',
    label: 'rocinante-12b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'inflection-3-productivity',
    label: 'inflection-3-productivity',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'inflection-3-pi',
    label: 'inflection-3-pi',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'text-embedding-3-large',
    label: 'text-embedding-3-large',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'text-embedding-3-small',
    label: 'text-embedding-3-small',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'text-embedding-ada-002',
    label: 'text-embedding-ada-002',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'noromaid-20b',
    label: 'noromaid-20b',
    provider: 'BothubRu',
    maxTokenAllowed: 2048,
  },
  {
    name: 'command-r-plus-08-2024',
    label: 'command-r-plus-08-2024',
    provider: 'BothubRu',
    maxTokenAllowed: 4000,
  },
  {
    name: 'palm-2-codechat-bison-32k',
    label: 'palm-2-codechat-bison-32k',
    provider: 'BothubRu',
    maxTokenAllowed: 32768,
  },
  {
    name: 'palm-2-chat-bison-32k',
    label: 'palm-2-chat-bison-32k',
    provider: 'BothubRu',
    maxTokenAllowed: 32768,
  },
  {
    name: 'palm-2-codechat-bison',
    label: 'palm-2-codechat-bison',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'palm-2-chat-bison',
    label: 'palm-2-chat-bison',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'l3.3-euryale-70b',
    label: 'l3.3-euryale-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'l3.1-euryale-70b',
    label: 'l3.1-euryale-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'l3.1-70b-hanami-x1',
    label: 'l3.1-70b-hanami-x1',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'l3-lunaris-8b',
    label: 'l3-lunaris-8b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'l3-euryale-70b',
    label: 'l3-euryale-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'jamba-1-5-mini',
    label: 'jamba-1-5-mini',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'jamba-1-5-large',
    label: 'jamba-1-5-large',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'jamba-instruct',
    label: 'jamba-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'phi-3.5-mini-128k-instruct',
    label: 'phi-3.5-mini-128k-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'phi-3-mini-128k-instruct',
    label: 'phi-3-mini-128k-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'phi-3-medium-128k-instruct',
    label: 'phi-3-medium-128k-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'hermes-3-llama-3.1-70b',
    label: 'hermes-3-llama-3.1-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'hermes-3-llama-3.1-405b',
    label: 'hermes-3-llama-3.1-405b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'hermes-2-pro-llama-3-8b',
    label: 'hermes-2-pro-llama-3-8b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'hyper-flux-8step',
    label: 'hyper-flux-8step',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'hyper-flux-16step',
    label: 'hyper-flux-16step',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'dolphin-mixtral-8x22b',
    label: 'dolphin-mixtral-8x22b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'dolphin-mixtral-8x7b',
    label: 'dolphin-mixtral-8x7b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mythomax-l2-13b',
    label: 'mythomax-l2-13b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mythomax-l2-13b:nitro',
    label: 'mythomax-l2-13b:nitro',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mythomax-l2-13b:extended',
    label: 'mythomax-l2-13b:extended',
    provider: 'BothubRu',
    maxTokenAllowed: 400,
  },
  {
    name: 'openchat-7b',
    label: 'openchat-7b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'toppy-m-7b',
    label: 'toppy-m-7b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'toppy-m-7b:nitro',
    label: 'toppy-m-7b:nitro',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'minimax-01',
    label: 'minimax-01',
    provider: 'BothubRu',
    maxTokenAllowed: 1000192,
  },
  {
    name: 'dbrx-instruct',
    label: 'dbrx-instruct',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'auto',
    label: 'auto',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'airoboros-l2-70b',
    label: 'airoboros-l2-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'xwin-lm-70b',
    label: 'xwin-lm-70b',
    provider: 'BothubRu',
    maxTokenAllowed: 400,
  },
  {
    name: 'mythalion-13b',
    label: 'mythalion-13b',
    provider: 'BothubRu',
    maxTokenAllowed: 400,
  },
  {
    name: 'weaver',
    label: 'weaver',
    provider: 'BothubRu',
    maxTokenAllowed: 1000,
  },
  {
    name: 'flux',
    label: 'flux',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'vetkastar',
    label: 'vetkastar',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'flux-fill-dev',
    label: 'flux-fill-dev',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'unslopnemo-12b',
    label: 'unslopnemo-12b',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'phi-3-mini-128k-instruct:free',
    label: 'phi-3-mini-128k-instruct:free',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'phi-3-medium-128k-instruct:free',
    label: 'phi-3-medium-128k-instruct:free',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'mythomax-l2-13b:free',
    label: 'mythomax-l2-13b:free',
    provider: 'BothubRu',
    maxTokenAllowed: 2048,
  },
  {
    name: 'openchat-7b:free',
    label: 'openchat-7b:free',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
  {
    name: 'toppy-m-7b:free',
    label: 'toppy-m-7b:free',
    provider: 'BothubRu',
    maxTokenAllowed: 2048,
  },
  {
    name: 'yi-large',
    label: 'yi-large',
    provider: 'BothubRu',
    maxTokenAllowed: 4096,
  },
];
